[phases.setup]
nixPkgs = ["nodejs_20", "git-lfs"]

[phases.install]
cmds = [
  "git lfs install",
  "git lfs pull",
  "npm install"
]

[phases.build]
cmds = ["bash build.sh"]

[start]
cmd = "node --import tsx api_server.ts"
